# Generated by Django 3.2.7 on 2022-02-09 07:44

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_otprequest_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='created',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='registration_date',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
    ]
