# Generated by Django 3.2.7 on 2022-02-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220209_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
