# Generated by Django 3.2.7 on 2022-02-28 09:19

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='registration_date',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
    ]
