# Generated by Django 3.2.7 on 2022-02-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sliders', '0003_alter_slider_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='slider_alt',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
