# Generated by Django 3.2.7 on 2022-02-09 07:44

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20220208_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_start_date',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
    ]
