# Generated by Django 3.2.7 on 2022-02-09 07:44

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_alt',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
    ]
