# Generated by Django 3.2.7 on 2022-02-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220209_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_alt',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
