# Generated by Django 3.2.9 on 2022-02-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_comment_vote'),
        ('shop_cart', '0002_cart_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ManyToManyField(related_name='product', to='course.Course'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.BigIntegerField(blank=True, default=1, null=True),
        ),
    ]
