# Generated by Django 3.2.7 on 2022-01-29 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_about_us', models.TextField(default='default about us')),
                ('footer_telegram', models.CharField(default='http://telegram.me/webasa', max_length=120)),
                ('footer_insta', models.CharField(default='http://insta.me/webasa', max_length=120)),
                ('footer_whats_app', models.CharField(default='http://whatsapp.me/webasa', max_length=120)),
                ('footer_phone', models.IntegerField(default='02598653269')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
