# Generated by Django 3.2.7 on 2022-02-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='footer_address',
            field=models.IntegerField(blank=True, default='02598653269', null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='footer_aparat',
            field=models.CharField(blank=True, default='http://whatsapp.me/webasa', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='footer_linkedin',
            field=models.CharField(blank=True, default='http://whatsapp.me/webasa', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='footer_twitter',
            field=models.CharField(blank=True, default='http://whatsapp.me/webasa', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='footer_youtube',
            field=models.CharField(blank=True, default='http://whatsapp.me/webasa', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='footer_about_us',
            field=models.TextField(blank=True, default='default about us', null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='footer_insta',
            field=models.CharField(blank=True, default='http://insta.me/webasa', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='footer_phone',
            field=models.IntegerField(blank=True, default='02598653269', null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='footer_telegram',
            field=models.CharField(blank=True, default='http://telegram.me/webasa', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='footer_whats_app',
            field=models.CharField(blank=True, default='http://whatsapp.me/webasa', max_length=120, null=True),
        ),
    ]
