# Generated by Django 3.2.7 on 2022-02-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0002_auto_20220201_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='footer_facebook',
            field=models.CharField(blank=True, default='https://www.facebook.com/webasa', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='footer_aparat',
            field=models.CharField(blank=True, default='https://www.aparat.com/webasa', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='footer_insta',
            field=models.CharField(blank=True, default='https://www.instagram.com/webasa', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='footer_linkedin',
            field=models.CharField(blank=True, default='https://www.aparat.com/webasa', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='footer_telegram',
            field=models.CharField(blank=True, default='http://www.telegram.me/webasa', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='footer_twitter',
            field=models.CharField(blank=True, default='https://twitter.com/webasa', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='footer_whats_app',
            field=models.CharField(blank=True, default='http://www.whatsapp.me/webasa', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='footer_youtube',
            field=models.CharField(blank=True, default='https://www.youtube.com/webasa', max_length=120, null=True),
        ),
    ]
