# Generated by Django 3.2.7 on 2022-02-09 07:44

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0003_auto_20220201_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
    ]
